apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fumo-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@chanyou.dev
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
