apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: headlamp
  namespace: kube-system
spec:
  repo: https://kubernetes-sigs.github.io/headlamp/
  chart: headlamp
  targetNamespace: headlamp
